### ISSUE TITLE
fix/기존 API 세부 사항 변경

### ISSUE THREAD

**Issue by rkdehdgns1230** [team-bukki/buki-backend#24]
# Issue Overview
iOS, FE 연동 과정에서 API 명세 변경에 따른 기존 API 수정

# TODO
- [x] 회원가입
- [ ] 홈
- [ ] 알림창
- [ ] 부적 생성
- [ ] 부적 상세
    - [x] 목표 달성
    - [ ] 부적 장착 정보
- [ ] 부적 편집
    - [ ] 부적 아이템 장착 정보
    - [ ] 소유 아이템 정보
    - [ ] 편집 완료
- [ ] 뽑기
    - [ ] 뽑기 가능 여부 파악
    - [ ] 뽑기 실행

**Comment by rkdehdgns1230** [comment]
- 회원가입 API 이름 정보 수신하도록 변경
- request body를 통해 데이터 받도록 변경
