### ISSUE TITLE
feature/item 관련 기능 구현

### ISSUE THREAD

**Issue by rkdehdgns1230** [team-bukki/buki-backend#25]
# Issue Overview
부적에 장착할 아이템 관련 API 개발 필요

# TODO
- [x] 특정 사용자가 보유한 아이템 리스트 조회 API
- [x] 아이템 선물 API
- [x] 아이템 지급 API
