### ISSUE TITLE
fix/회원 API 개선 및 신규 개발

### ISSUE THREAD

**Issue by rkdehdgns1230** [team-bukki/buki-backend#26]
# Issue Overview
회원 가입 경로 추가에 따른 기존 유저 API 개선

# TODO
- [x] 회원 삭제 API 개발
    - [x] userId 이용한 개발용 삭제 API
    - [x] 토큰 이용한 상용 계정 삭제 
- [x] 회원 조회에서 LoginType 조회 가능하도록
- [x] 유저별 친구 추가를 위한 식별 코드 생성 로직 변경
- [x] 회원 조회 authProviderId 제외
    - [x] authProviderId -> platformProviderId 변경
- [x] 친구 리스트 조회 API 개발
    - [x] 친구 ID, 친구가 진행 중인 카테고리 목록, 프로필 이미지 프리셋 정보 
    - [x] 친구 삭제 논리적 삭제 처리
    - [x] 친구 추가를 위한 토큰 조회 API (유저) => getUser로 대체
- [x] 토큰 발급 방식 개선
    - [x] 기존 토큰 발급 API 유효 기간 100일로 증가 
    - [x] 테스트용 유효 기간 짧은 API 추가 개발
    - [x] jwt 키 값 변경

**Comment by rkdehdgns1230** [comment]
- userId 이용한 개발용 삭제 API 구현
- LoginType 조회 가능하도록 추가
- authProviderId 제공 삭제 및 명칭 platformProviderId로 변경

**Comment by rkdehdgns1230** [comment]
- 사용자 계정 삭제 API 개발
- jwt 발급 개선
- todo: jwt 보안 강화 필요

**Comment by Juhwa-Lee1023** [comment]
@rkdehdgns1230 
getUser api path 수정 필요할듯

정상 response
```
curl -X 'GET' \
  'http://13.125.146.145:8080/api/v1/users/{userId}?userId=4' \
  -H 'accept: */*' \
  -H 'Authorization: Bearer []'
{"status":"OK","code":"G000","message":"요청에 성공했습니다.","result":{"userId":4,"loginType":"APPLE","firstName":"주화","lastName":"이","code":"c00889ca7611441e9a0cdd95e6278af1","authority":"USER","createdAt":"2024-04-22T14:32:15.279348","lastUpdatedAt":"2024-04-22T14:32:15.279348","pushToken":"e4lm2_z5kvXgVsI0HAGD_i:APA91bGOGwefTOnHLsupVv-PFaSacoYr3yWhKPneGQsyEi2DuIQ8ymSbk-kPJXTkr4cbuC8Dx_7k48ubyPPGspnRWDBgnJGxa82SOO9ayq_wtUwvgoIALov-sJNbn4RtcXQGVT33dWoL"}}%
```

잘못된 response
```
curl -X 'GET' \
  'http://13.125.146.145:8080/api/v1/users/4' \
  -H 'accept: */*' \
  -H 'Authorization: Bearer []'
{"status":"BAD_REQUEST","code":"G310","message":"유저가 유효하지 않습니다."}%
```

확인 한번 부탁..!

**Comment by Juhwa-Lee1023** [comment]
getUser에서 이메일도 같이 내려줘야됨..!

<img width="334" alt="image" src="https://github.com/team-bukki/buki-backend/assets/63584245/a56c3511-ee9e-4496-bfd4-e8bd8e387a08">

**Comment by rkdehdgns1230** [comment]
@Juhwa-Lee1023 지금 회원 가입 할 때 이메일 주소를 받는 형태인가요??
현재 entity에 email 정보를 저장하고 있지 않아서, 만약 그렇다면 회원가입 쪽에서 입력 받을 수 있도록 추가 수정도 필요할 것 같음

**Comment by Juhwa-Lee1023** [comment]
@rkdehdgns1230 ㄴㄴ 같이 안받고 있음

<img width="307" alt="image" src="https://github.com/team-bukki/buki-backend/assets/63584245/4c22662c-4a47-46b2-b112-f7b279994e37">

**Comment by rkdehdgns1230** [comment]
email 대신 LoginType 표현하는 것으로 대체 처리
