### ISSUE TITLE
feature/뱃지 API 개발

### ISSUE THREAD

**Issue by rkdehdgns1230** [team-bukki/buki-backend#27]
# Issue Overview
뱃지 서비스 제공을 위한 API 개발 필요

# TODO
- [x] 뱃지 리스트 조회 API
    - [x] 뱃지 정보 조회 시 획득 날짜 정보와 뱃지 식별자만 보내면 된다. 
    - [x] 뱃지 리스트 조회할 당시에만 뱃지 조건 달생 여부 확인한다.
    - [x] 개별 뱃지 부여할 수 있는 수단 추가 검토

뱃지 관련 API 스펙 검토 필요

**Comment by rkdehdgns1230** [comment]
Badge는 Entity가 아닌 Enum으로 관리하며,

이유는 다음과 같다.

- 서비스 중 뱃지가 추가되는 경우 많지 않음
- 설령 추가 된다고 하더라도, 서비스 도중에 CUD(Create, Update, Delete) 작업하는 케이스 거의 없을 것으로 예상
- 즉, 배포 도중 변경되는 케이스 없을 것 (하다 못해 버전이 변경됨에 따라서 뱃지 정보가 변경될 것)

참고만 해주세여

cc. @suker80 @Juhwa-Lee1023 @ohhamin

**Comment by rkdehdgns1230** [comment]
API 응답으로는 badge 이름(제 임의로 지었음), 기획에서 정의한 이름, 뱃지 id, 뱃지 설명, 뱃지 팁 등의 정보를 묶어 전달 하도록 개발 중
