### ISSUE TITLE
feature/부적 API 개발

### ISSUE THREAD

**Issue by rkdehdgns1230** [team-bukki/buki-backend#28]
# Issue Overview
완성 부적 정보 제공을 위한 API 개발

# TODO
- [ ] 완성된 상태의 장착 아이템 스냅샷 정보, 이름, 완성 일자, 장착템 정보 제공 API 필요
- [ ] 부적 세부 조회 API 개선
- [ ] 부적 리스트 조회 API 개선
- [x] 부적 일일 목표 완료 API 개발
- [x] 부적 생성 API 개발

**Comment by rkdehdgns1230** [comment]
@suker80 여기 이슈 보면서 개발해주삼여

**Comment by rkdehdgns1230** [comment]
@suker80 이슈 이미 있습니다.

**Comment by rkdehdgns1230** [comment]
부적 상태 관리를 위한 필드 추가 필요해보입니다. (e,g, isCompleted = true(완성), false(만드는 중))
- 부적을 21일까지 수행(complete)한 상태와 '완성'한 상태는 별개
- 이는 부적을 '완성'한 경우 수정을 하지 못하도록 하기 위함
- '완성'전까지는 부적 꾸미기 작업을 유저가 자유롭게 할 수 있도록 하기 위함
cc. @suker80 @Juhwa-Lee1023 @ohhamin
